### ISSUE TITLE
Error trying to download electricity dataset

### ISSUE THREAD

**Issue by jason-d-jones** [LeoGrin/tabular-benchmark#1]
Hello LeoGrin,

I saw a paper that referenced this and was trying to download the data. I have successfully downloaded a few of them using the download data function:
```
% python data/download_data.py
```

However, I am getting an error that I do not know how to resolve when it is trying to download the electricity dataset (at least I think that is the one it is having trouble with).

```
WARNING:root:Received uncompressed content from OpenML for https://api.openml.org/data/v1/download/22103245/electricity.arff.
Downloading dataset electricity
Traceback (most recent call last):
  File "data/download_data.py", line 34, in <module>
    save_suite(suites_id["numerical_classification"],
  File "data/download_data.py", line 16, in save_suite
    y = np.array(y).astype(np.int32)
ValueError: invalid literal for int() with base 10: 'DOWN'
```

I am using Python 3.8.8 on macOS.

Do you know what might be causing this?

Jason

**Comment by k-harada** [comment]
Hi LeoGrin,

Tabular-benchmark data is very meaningful and I would like to reproduce them somehow.  

I am getting the same error as Jason on Kaggle Notebook.   
These datasets also give same ValueError on int.  
`[
    "electricity", "pol", "house_16H", "kdd_ipums_la_97-small", 
    "MagicTelescope", "KDDCup09_upselling", "road-safety"
]`
I guess the code that handles the binarization for original data is missing.  

Kei Harada

**Comment by LeoGrin** [comment]
Hi, 
Thanks for the feedback! It should be solved :)
