### ISSUE TITLE
Paper performance missing

### ISSUE THREAD

**Issue by abvesa** [LeoGrin/tabular-benchmark#10]
Hello LeoGrin,

First thanks for the very good work.
I was trying to reproduce paper's result using the data you provided in ./analyses/results/, 
and the R scripts you provided in ./analyses.

however, I found that some of the performance are missing:
(1) SAINT performance of "medium-sized categorical regression" datasets
(2) MLP perfomance of all datasets

I'm wondering if you can provide the missing performances for the full reproduction of paper's experimental results,
thank you.

**Comment by LeoGrin** [comment]
The missing part is now available, you can run `curl -L -o analyses/results/benchmark_total.csv https://figshare.com/ndownloader/files/40081681` to download the random search results.
