### ISSUE TITLE
Is any of the datasets used highly imbalanced?  

### ISSUE THREAD

**Issue by Aml-Hassan-Abd-El-hamid** [LeoGrin/tabular-benchmark#11]
Great work on that paper!
I see that you have used many datasets, and I have a question: Is any of those datasets used highly imbalanced?

**Comment by Sandy4321** [comment]
good question 
seems to be not 
then this material is not serious

**Comment by lcrmorin** [comment]
Data sets are balanced

**Comment by amir-zeraati** [comment]
If I remember correctly, at least "Covertype" is imbalanced! Unless the writers used only part of it to be able to be balanced.
