### ISSUE TITLE
will it work for windows,?

### ISSUE THREAD

**Issue by Sandy4321** [LeoGrin/tabular-benchmark#15]
will it work for windows, 
since at least files downloading gives path error for windows

**Comment by LeoGrin** [comment]
Thanks for pointing it out! It should work on Windows. I did a refactoring quite recently, changing how data are downloaded, so I'm hoping it fixes your issue.

**Comment by Sandy4321** [comment]
can it be used as stand alone without WandB  ?
if not 
do you know similar stand alone project
