### ISSUE TITLE
Can't download RandomSearch results CSVs

### ISSUE THREAD

**Issue by Raphaaal** [LeoGrin/tabular-benchmark#17]
Hi, 

Thanks a lot for this thorough work. 

I wanted to fetch the results CSVs for all random search iterations (in ``./analyses/results/*.csv``), however, I am facing the following error:

Command: ``git lfs fetch``
Response:
```
Fetching main
Git LFS: (0 of 5 files) 0 B / 835.74 MB 
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/LeoGrin/tabular-benchmark.git/info/lfs'
``` 

Could you please point me to another location where you could share the results of your random searches? 

Thanks a lot in advance.

Best,

**Comment by Epanemu** [comment]
Hello, I have the same issue. Trying to obtain the categorical results only, I get the following error:

```
$ git lfs pull --include analyses/results/random_search_benchmark_categorical.csv 
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.                                        
Failed to fetch some objects from 'https://github.com/LeoGrin/tabular-benchmark.git/info/lfs'
```

Could you share the results elsehow? Thank you very much.

**Comment by LeoGrin** [comment]
Sorry there was an issue with git lfs, this is fixed now. You can download the random search results using `curl -L -o analyses/results/benchmark_total.csv https://figshare.com/ndownloader/files/40081681`
