### ISSUE TITLE
Error in import_open_ml_data - All features are categorically encoded

### ISSUE THREAD

**Issue by manujosephv** [LeoGrin/tabular-benchmark#18]
Hi,

I was trying to use the benchmark to test a few algorithms, and while I was preparing the experiment, ran into [this line](https://github.com/LeoGrin/tabular-benchmark/blob/0ed27232b61191e60b7e357c664426d1f98435c7/src/generate_data.py#L52) in the  `import_open_ml_data` method.

```python
# Replace categorical values by integers for each categorical column
    for i, categorical in enumerate(categorical_indicator):
        X.iloc[:, i] = X.iloc[:, i].astype('category')
        X.iloc[:, i] = X.iloc[:, i].cat.codes
        X.iloc[:, i] = X.iloc[:, i].astype('int64')
```
`categorical_indicator` is a boolean array of the same length of the features. Isn't this converting all features (continuous and categorical) into a label encoded form?

<s>And if this is a problem, how much impact is there to the benchmarks and paper published?</s>
I guess this method wasn't used in the benchmark. Was using 'import_openml_data_no_transform` instead.

**Comment by LeoGrin** [comment]
Hi, thanks for raising this issue. Indeed there is a "if categorical" missing, but the function isn't used in the benchmark. I've deleted it to make it clearer. If you're interested in the preprocessing: https://github.com/LeoGrin/tabular-benchmark/blob/main/src/preprocessing/preprocessing.py

**Comment by manujosephv** [comment]
Thanks for the quick reply..I raised the issue initially when I thought it was being used in the benchmark! Phew..

Anyways, I think I'm going to use the `train_model_on_config` [here](https://github.com/LeoGrin/tabular-benchmark/blob/670c3bd7991351be0b4b85942967334c7d4d3fb2/src/run_experiment.py#LL30C5-L30C26) along with the config from the uploaded excel benchmark to make my results comparable to the benchmark. Would that work? I don't have a sci-kit learn model and was thinking if I can edit the train model part, I can get around that limitation?

**Comment by manujosephv** [comment]
I meant the excel benchmark, which is the wandb export where you save the config.. I'm thinking of using that as a template for the config and change only the ones i have to...
