### ISSUE TITLE
Running custom model

### ISSUE THREAD

**Issue by AnFreTh** [LeoGrin/tabular-benchmark#24]
Hi,
great paper!

how can I compare a custom model, without using WandB? 
From your documentation it seems like it is necessary to have a WandB subscription?

**Comment by LeoGrin** [comment]
Thanks!

Yes, to use the whole code you need to use WandB unfortunately, but you
shouldn't need any paying subscription.

**Comment by AnFreTh** [comment]
Alright, thanks for the answer. 
I'll close this issue. :)
