### ISSUE TITLE
Package dependencies

### ISSUE THREAD

**Issue by hankook** [LeoGrin/tabular-benchmark#3]
Thanks for this meaningful project in the field of tabular deep learning!

Could you let me know the package dependencies for this project? It would be better if such information is specified in README.

**Comment by jpodivin** [comment]
I believe the dependencies for the python code can be found in [requirements.txt](https://github.com/LeoGrin/tabular-benchmark/blob/main/src/requirements.txt). But I'm not sure about the rest.

**Comment by hankook** [comment]
Oh, I didn't know that. Thanks!
