### ISSUE TITLE
Commented out code in Resnet and MLP

### ISSUE THREAD

**Issue by Kunal458** [LeoGrin/tabular-benchmark#5]
I was looking to benchmark the datasets with the given deep learning models and I found that much of the code is commented out in bin/mlp.py and resnet.py. Would the code work without the commented code, and is there any reason for it like fixing some errors in them?

**Comment by LeoGrin** [comment]
The code for these two models is adapted from https://github.com/Yura52/rtdl. I kept their model architecture and commented out the rest of their code (data loading etc), which I deal with separately.

**Comment by Kunal458** [comment]
Alright understood. Thanks!
