### ISSUE TITLE
Are you open for contributions?

### ISSUE THREAD

**Issue by tiagofrepereira2012** [LeoGrin/tabular-benchmark#7]
Hi, 

First thanks for the very good work and for making it opensource.

I'm trying to run it locally (via the `src/run_script.py`) on my computer and facing several errors (from missing dependencies to missing keys in the `config` dictionary).

I'm fixing them one by one and I'm wondering if you are open to accept pull requests

Thanks

**Comment by LeoGrin** [comment]
Hi,

Thank you for the suggestion, I do accept pull requests !
